name: Flutter GD test Release app CI

on:
  release:
    types: [published]

jobs:
  build:
    name: Flutter GD test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: 'stable'
          cache: true
        
      - name: Install dependencies
        run: flutter pub get

      - name: Dart linter
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Start release build
        run: flutter build appbundle

      - name: Publish Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./build

