name: Flutter GD test Web Release app CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Flutter GD test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
          cache-dependency-path: |
            android/*.gradle*
            android/**/*.gradle*
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: 'stable'
          cache: true
        
      - name: Install dependencies
        run: flutter pub get

      - name: Dart linter
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test

      # - name: Deploy to GitHub pages
      #   uses: bluefireteam/flutter-gh-pages@v7
      #   with:
      #     baseHref: /hi_flutter/
      # Workig alternative of everything below (without saving artifact)

      - name: Start web release build
        run: flutter build web --release --base-href "/hi_flutter/"
      
      - name: Publish Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./build/web
      

  deploy_gh:
    name: Flutter GD test deploy to GitHub pages
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release
      uses: actions/download-artifact@v4
      with:
        name: web-release

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./