name: Flutter GD test Web Release app CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Flutter GD test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: 'stable'
          cache: true
        
      - name: Install dependencies
        run: flutter pub get

      - name: Dart linter
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Start web release build
        run: flutter build web --release

      - name: Publish Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./build

  deploy_gh:
    name: Flutter GD test deploy to GitHub pages
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release
      uses: actions/download-artifact@v4
      with:
        name: web-release

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: web
